version: "3"

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Csridhar2601@
    volumes:
      - db_data:/var/lib/mysql
  loader:
    build: .
    depends_on:
      - db
    volumes:
      - ./data:/data

volumes:
  db_data:
